<?php
use Learning\AdditionalDescription\Block\Product\Description;

/** @var Description $block */

$descriptions = $block->getDescriptionList();
?>
<div id="additional-description-block" class="additional-description-block">
    <div class="block-content">
        <?php if ($block->canCustomerAddDescription()) : ?>
            <a class="action primary add-description open-modal-form"
                href="#">
                <?= __('Add')?>
            </a>
        <?php endif; ?>
        <?php if (count($descriptions) > 0) : ?>
            <?php foreach ($descriptions as $description) :?>
                <div class="description">
                    <div class="content">
                        <?php echo $block->escapeHtml($description->getAdditionalDescription()) ?>
                    </div>
                    <div class="footer">
                        <div class="actions">
                            <?php if ($block->isEditButtonVisible($description)) : ?>
                                <a class="action primary edit-description open-modal-form"
                                   data-id="<?= $description->getAdditionalDescriptionId() ?>"
                                   href="#">
                                    <?= __('Edit')?>
                                </a>
                            <?php endif;?>
                        </div>
                        <div class="author">
                            <?php echo $block->escapeHtml($description->getCustomerEmail()) ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <?php echo $block->getChildHtml() ?>
    </div>
</div>
