<?php

use Learning\Blog\Api\Data\BlogInterface;
use Learning\Blog\Block\Blog;
use Magento\Framework\Api\SortOrder;

/** @var Blog $block */

$items = $block->getItems(5, SortOrder::SORT_DESC);
?>

<?php if ($block->showBlogSection() && count($items) > 0) : ?>
    <div class="product info related-blogs">
        <p class="header">Top 5 latest posts</p>
        <?php foreach ($items as $item) : ?>
            <?php /** @var BlogInterface $item */ ?>
            <div class="blog-item">
                <div class="header">
                    <span class="publish-date">
                        <?php echo $block->formatDate(
                            $item->getCreatedAt() ?? '',
                            \IntlDateFormatter::SHORT,
                            true
                        ) ?>
                    </span>
                </div>
                <div class="image-block">
                    <a href="#" src="" title="<?php echo $block->escapeHtml($item->getSubject()) ?>">
                        <img
                            src="<?php echo $block->fullImgPath($item->getImageUrl()) ?>"
                            alt="blog-image"
                            width="100"
                            height="100"
                        />
                    </a>
                </div>
                <div class="content-block">
                    <a href="#" class="subject"><?php echo $block->escapeHtml($item->getSubject()) ?></a>
                    <p class="content"><?php echo $block->escapeHtml($item->getContent()) ?></p>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
