<?php

use Learning\Blog\Block\Blog;
use Magento\Framework\Api\SortOrder;

/** @var Blog $block */

$items = $block->getItems(5, SortOrder::SORT_DESC);
?>

<?php if ($block->showBlogSection() && count($items) > 0) :?>
    <div class="product info related-blogs">
        <div class="blog-item">
            <div class="row">
                <div class="col-md-4">
                    <div class="image">
                        image
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row publish-date"></div>
                    <div class="row subject"></div>
                </div>
            </div>
        </div>

        <?php foreach ($items as $item) :?>
            <div class="blog-item">
                <?php print_r($item->getSubject())?>
            </div>
        <?php endforeach; ?>

    </div>
<?php endif; ?>
